spring.application.name=Ladino-Barber

admin.id=admin-ladino-barber
admin.nombre=Administrador
admin.correo=admin@ladinobarber.com
admin.telefono=+573000000000
admin.password=${ADMIN_PASSWORD:cambiar_en_produccion}
